apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: soft-pos-service
  namespace: card-processing
spec:
  hosts:
    - dev-pos-soft.unibank.lan
  gateways:
    - pos-soft
  http:
    - name: "pos-soft-vs"
#      match:
#        - uri:
#            prefix: "/SoftPos"
#      rewrite:
#        uri: "/"
      route:
        - destination:
            host: soft-pos-service.card-processing.svc.cluster.local
            port:
              number: 8082
