logging:
  level:
    az:
      unibank:
        softpos: TRACE

application:
  endpointDefault: http://10.142.0.11:10017
  initiatorRidDefault: TEST
springfox:
  documentation:
    auto-startup: true
    swagger-ui:
      enabled: true
request:
  header: Authorization
  prefix: SOFT_POS_
  timeout: 86400000
#  timeout: 30000
  user: pos-creator
  password: SAJJWTQVVWIMW7EI9SDPZFGEBZ4FMPRLTYNXWTPTWGH4MMRYUORWIIFY33Z2MHD3