logging:
  level:
    az:
      unibank:
        softpos: TRACE

application:
  endpointDefault: http://10.142.0.11:10017
  initiatorRidDefault: TEST
springfox:
  documentation:
    auto-startup: true
    swagger-ui:
      enabled: true
request:
  user: pos-creator
  header: Authorization
  prefix: SOFT_POS_
  password: NBpCnAHDj6IrUgEtxDW9xhwkQuxxF34R
  timeout: 31536000
