spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  application:
    name: SOFT API

  security:
    user:
      name: admin
      password: 12345
      roles: admin

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - health
          - prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true

  server:
    port: 8080
  service:
    STANDARD_TIMEOUT: 10000
server:
  error:
    include-message: always
