apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: soft-pos
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: soft-pos
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
